/*
 * PSD2 Demo
 *
 * Demo application for PSD2
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: noreply@example.com
 * Generated by: https://openapi-generator.tech
 */

/// Coord : Coordinates



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Extract, Response)]
pub struct Coord {
    /// row number
    #[serde(rename = "row")]
    pub row: i32,
    /// column number
    #[serde(rename = "col")]
    pub col: i32,
}

impl Coord {
    /// Coordinates
    pub fn new(row: i32, col: i32) -> Coord {
        Coord {
            row,
            col,
        }
    }
}


