/*
 * PSD2 Demo
 *
 * Demo application for PSD2
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: noreply@example.com
 * Generated by: https://openapi-generator.tech
 */

/// TableUpdateResponse : Response for a TableUpdateRequest.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Response)]
pub struct TableUpdateResponse {
    /// Semantic versioning information (MAJOR.MINOR.PATCH).
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "table")]
    pub table: crate::models::ErrorTable,
}

impl TableUpdateResponse {
    /// Response for a TableUpdateRequest.
    pub fn new(version: String, table: crate::models::ErrorTable) -> TableUpdateResponse {
        TableUpdateResponse {
            version,
            table,
        }
    }
}


